name: Java CI/CD Pipeline with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Print Docker Username
        run: |
          echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"

      - name: Build Docker image
        run: |
          echo "Building Docker image for ${{ secrets.DOCKER_USERNAME }}/fan_control-tripwonder:latest"
          docker build -t fan_control-tripwonder:latest .
          docker images  # In ra tất cả các Docker images sau khi build để kiểm tra

      - name: Print Build Success Message
        run: echo "Docker image built successfully."

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Print Docker Images List (After Build)
        run: docker images  # In ra danh sách image trước khi push

      - name: Push Docker image to Docker Hub
        run: docker push wiramin/fan_control-tripwonder:latest
#          docker tag fan_control-tripwonder:latest wiramin/fan_control-tripwonder:latest
          

      - name: Print Push Success Message
        run: echo "Docker image pushed to Docker Hub successfully."
